# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
# SPDX-License-Identifier: Apache-2.0

[project]
authors = [
    "Aaron Fanous <aron7628@stanford.edu>",
    "Shlok Natarajan <shlok.natarajan@gmail.com>"
]
channels = ["conda-forge"]
name = "AutoGKB"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
seaborn = ">=0.13.2,<0.14"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.3,<3"
biopython = ">=1.85,<2"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.5,<3"
openai = ">=1.76.2,<2"
playwright = ">=1.52.0,<2"
loguru = ">=0.7.2,<0.8"
