# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
# SPDX-License-Identifier: Apache-2.0

[project]
authors = [
    "Aaron Fanous <aron7628@stanford.edu>",
    "Shlok Natarajan <shlok.natarajan@gmail.com>"
]
channels = ["conda-forge"]
name = "AutoGKB"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
download-variants = "python -m src.load_variants.load_clinical_variants"
update-download-map = "python -c 'from src.fetch_articles.article_downloader import update_downloaded_pmcids; update_downloaded_pmcids()'"
download-articles = "python -m src.fetch_articles.article_downloader"

[dependencies]
seaborn = ">=0.13.2,<0.14"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.3,<3"
biopython = ">=1.85,<2"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.5,<3"
openai = ">=1.76.2,<2"
playwright = ">=1.52.0,<2"
loguru = ">=0.7.2,<0.8"
python-dotenv = ">=1.1.0,<2"
black = ">=25.1.0,<26"
