# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
# SPDX-License-Identifier: Apache-2.0

[project]
authors = [
    "Aaron Fanous <aron7628@stanford.edu>",
    "Shlok Natarajan <shlok.natarajan@gmail.com>"
]
channels = ["conda-forge"]
name = "AutoGKB"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
download-variants = "python -m src.load_variants.load_clinical_variants"
update-download-map = "python -c 'from src.fetch_articles.article_downloader import update_downloaded_pmcids; update_downloaded_pmcids()'"
download-articles = "python -m src.fetch_articles.article_downloader"
download-data = "gdown --fuzzy https://drive.google.com/file/d/1qtQWvi0x_k5_JofgrfsgkWzlIdb6isr9/view && unzip autogkb-data.zip && rm autogkb-data.zip"
setup-repo = "pixi install && pixi run download-data"
copy-markdown = "python -m src.copy_markdown"
annotation-pipeline = "python -m src.annotation_pipeline"
test-citations = "python -m src.citations.one_shot_citations"

[dependencies]
seaborn = ">=0.13.2,<0.14"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.3,<3"
biopython = ">=1.85,<2"
ipykernel = ">=6.29.5,<7"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.5,<3"
openai = ">=1.76.2,<2"
playwright = ">=1.52.0,<2"
loguru = ">=0.7.2,<0.8"
python-dotenv = ">=1.1.0,<2"
black = ">=25.1.0,<26"
datasets = ">=3.6.0,<4"
litellm = ">=1.72.2,<2"
termcolor = ">=3.1.0,<4"
gdown = ">=5.2.0,<6"
google-auth = ">=2.40.3,<3"
